In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [30]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [31]:
data= data.drop(['RowNumber','CustomerId','Surname'], axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
# Encode categorical var
lable_encode_gender = LabelEncoder()
data['Gender']= lable_encode_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [33]:
data['Geography'].value_counts()
# one hot encode geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [34]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [35]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [36]:
#  combine one hot encoded column with original data
data= pd.concat([data.drop('Geography', axis = 1), geo_encoded_df], axis = 1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [37]:
# save encoders and scalers

with open('lable_encode_gender.pkl','wb') as f:
    pickle.dump(lable_encode_gender, f)

with open('onehot_encoder_geo.pkl','wb') as f:
    pickle.dump(onehot_encoder_geo, f)

In [38]:
# divide data into independent and dependent feature

X = data.drop('Exited',axis = 1)
y = data['Exited']

#  split traing and testing set

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [39]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [40]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [41]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

#### ANN Implementation

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [43]:
# build model

model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)), # hl1 connected with i/p layer
    Dense(32, activation = 'relu'),                                    # hl1
    Dense(1, activation = 'sigmoid')   # o/p layer
])

In [44]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [45]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [46]:
## compile the model 
model.compile(optimizer=opt,loss="binary_crossentropy", metrics=['accuracy'])

In [47]:
# set up tensorboard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [48]:
# set up early stopping
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience=10, restore_best_weights=True)

In [49]:
#  train model
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test),
    epochs = 100, callbacks = [tensorflow_callback,early_stopping_callback]
    )

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3970 - accuracy: 0.8349 - val_loss: 0.3648 - val_accuracy: 0.8575
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3531 - accuracy: 0.8572 - val_loss: 0.3666 - val_accuracy: 0.8540
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3477 - accuracy: 0.8602 - val_loss: 0.3446 - val_accuracy: 0.8610
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3474 - accuracy: 0.8565 - val_loss: 0.3484 - val_accuracy: 0.8575
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3404 - accuracy: 0.8619 - val_loss: 0.3541 - val_accuracy: 0.8600
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3380 - accuracy: 0.8611 - val_loss: 0.3409 - val_accuracy: 0.8615
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3359 - accuracy: 0.8639 - val_loss: 0.3480 - val_accuracy: 0.8555
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3326 - accuracy: 0.8641 - val_loss: 0.3478 - val_accuracy: 0.8605
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3311 - accuracy: 0.8644 - val_loss: 0.3401 - val_accuracy: 0.8625
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.8648 - val_loss: 0.3424 - val_accuracy: 0.8635
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3294 - accuracy: 0.8661 - val_loss: 0.3375 - val_accuracy: 0.8565
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3255 - accuracy: 0.8676 - val_loss: 0.3494 - val_accuracy: 0.8545
Epoch 13/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3235 - accuracy: 0.8674 - val_loss: 0.3501 - val_accuracy: 0.8610
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3204 - accuracy: 0.8679 - val_loss: 0.3476 - val_accuracy: 0.8585
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3196 - accuracy: 0.8690 - val_loss: 0.3370 - val_accuracy: 0.8620
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3166 - accuracy: 0.8685 - val_loss: 0.3464 - val_accuracy: 0.8570
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3129 - accuracy: 0.8709 - val_loss: 0.3493 - val_accuracy: 0.8625
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3097 - accuracy: 0.8717 - val_loss: 0.3535 - val_accuracy: 0.8570
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3081 - accuracy: 0.8725 - val_loss: 0.3531 - val_accuracy: 0.8630
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3062 - accuracy: 0.8748 - val_loss: 0.3524 - val_accuracy: 0.8595
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3037 - accuracy: 0.8758 - val_loss: 0.3588 - val_accuracy: 0.8625
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2986 - accuracy: 0.8759 - val_loss: 0.3667 - val_accuracy: 0.8615
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2988 - accuracy: 0.8755 - val_loss: 0.3629 - val_accuracy: 0.8580
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2984 - accuracy: 0.8773 - val_loss: 0.3617 - val_accuracy: 0.8630
Epoch 25/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2921 - accuracy: 0.8764 - val_loss: 0.3645 - val_accuracy: 0.8540

In [50]:
model.save('model.h5')

c:\Users\Tejaswini\OneDrive\Desktop\Gen AI\Sec 13 14\AnnProject\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [51]:
# load tensorboard
%reload_ext tensorboard

In [52]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6007 (pid 20636), started 0:03:11 ago. (Use '!kill 20636' to kill it.)

In [ ]:
#  Load pickle file